### ISSUE TITLE
should mirage-stdlib-random be part of this

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage-random#1]
atm [`mirage-stdlib-random`](https://github.com/hannesm/mirage-stdlib-random) is its own opam package and repository, and wraps OCaml standard library `Random` into Mirage `V1.RANDOM`.

I think it would be a good submodule of this library here, please tell me if you've a different opinion (esp. @samoht)

OTOH [`randomconv`](https://github.com/hannesm/randomconv) should be kept in its own repository (nothing Mirage specific in there), similar to `duration` and `mirage-clock`.

**Comment by samoht** [comment]
yes, that seems a good idea to consolidate mirage-related helpers around RANDOM here.

**Comment by hannesm** [comment]
done
